name: Atualizar Clima

on:
  schedule:
    - cron: '*/30 * * * *'  # Roda a cada 30 minutos
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Instalar dependências (nenhuma nesse caso)
      run: echo "Nada para instalar"

    - name: Rodar script de clima
      run: node get-weather.js

    - name: Commit e push do JSON
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add weather.json
        if git diff --cached --quiet; then
          echo "Nada para commitar"
        else
          git commit -m "Atualizar clima automaticamente"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:master

        fi
