name: Atualizar Clima

on:
  schedule:
    - cron: '*/30 * * * *'  
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout com permissão para push
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Rodar script de clima
        run: node get-weather.js

      - name: Commit e push do JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add weather.json
          if git diff --cached --quiet; then
            echo "Nada para commitar"
          else
            git commit -m "Atualizar clima automaticamente"
            git push origin HEAD:${{ github.ref_name }}
          fi

